## This assignment demonstrates the scoping rules
## of R. Our goal is to invert an input square 
## matrix. If this inverse has not yet been calculated,
## R should calculate the inverse and save it to the
## cache. Otherwise, ## R should retrieve the inverse
## from the cache.


## Creates a list of functions, which serves as the input
## to cacheSolve()
makeCacheMatrix <- function(x = matrix()) {
  ## inputs
  ## x: matrix
  ## outputs
  ## list: list of functions
  
  # default assignment 
  # (so getinv() will return NULL if not calculated yet)
  inv <- NULL
  
  # function to get the value of the matrix
  set <-function(y) {        
    x <<- y
    inv <<- NULL
  }
  # function to set the value of the matrix
  get <- function() x
  # function to set the value of the inverse
  setinv <- function(solve) inv <<- solve
  #function to get the value of the inverse
  getinv <- function() inv
  
  # list of all functions
  list(set = set, 
       get = get,
       setinv = setinv,
       getinv = getinv)
}


## Calculates the matrix inverse, or, if it has been
## calculated before, retrieves it from the cache
cacheSolve <- function(x, ...) {
  ## inputs:
  ## x: list of functions, generated by makeCacheMatrix
  inv <- x$getinv()
  # check if the inverse has been calculated yet
  ## if so, retrieve its value from the cache
  if(!is.null(inv)) {
    message("getting cached data")
    return(inv)
  }
  # calculate inverse
  data <- x$get()
  inv <- solve(data)
  
  # save the inverse in the cache
  x$setinv(inv)
  
  inv
}
